version: '3'

services:
  cache: 
    image: redis:alpine
    ports:
      - '6379:6379'
    command: ['--requirepass "secret"']
    restart: "always"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: authentication
      MONGO_USERNAME: admin
      MONGO_PASSWORD: secret
    ports:
      - 27018:27017
    volumes:
      - ./data:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/